// <auto-generated />
using System;
using GrupoBJ.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrupoBJ.Migrations
{
    [DbContext(typeof(GrupoBJDBContext))]
    [Migration("20200828220719_Empresa-Actualizacion-Ciudad-2")]
    partial class EmpresaActualizacionCiudad2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrupoBJ.Models.Ciudad", b =>
                {
                    b.Property<int>("idCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bHabilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dFechaUsuarioCreo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dFechaUsuarioModifico")
                        .HasColumnType("datetime2");

                    b.Property<int>("fkEstado")
                        .HasColumnType("int");

                    b.Property<int>("fkUsuarioCreo")
                        .HasColumnType("int");

                    b.Property<int>("fkUsuarioModifico")
                        .HasColumnType("int");

                    b.Property<string>("sNombreCiudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCiudad");

                    b.HasIndex("fkEstado");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("GrupoBJ.Models.Empresa", b =>
                {
                    b.Property<int>("idEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bHabilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaUsuarioCreo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaUsuarioModifico")
                        .HasColumnType("datetime2");

                    b.Property<int>("fkCiudad")
                        .HasColumnType("int");

                    b.Property<int>("fkMoneda")
                        .HasColumnType("int");

                    b.Property<int>("fkUsuarioCreo")
                        .HasColumnType("int");

                    b.Property<int>("fkUsuarioModifico")
                        .HasColumnType("int");

                    b.Property<string>("sCalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sCardinalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sCodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sColonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sFax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sIdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("sNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sNumeroExterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sNumeroInterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sRazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEmpresa");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("GrupoBJ.Models.Estado", b =>
                {
                    b.Property<int>("idEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bHabilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dFechaUsuarioCreo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dFechaUsuarioModifico")
                        .HasColumnType("datetime2");

                    b.Property<int>("fkPais")
                        .HasColumnType("int");

                    b.Property<int>("fkUsuarioCreo")
                        .HasColumnType("int");

                    b.Property<int>("fkUsuarioModifico")
                        .HasColumnType("int");

                    b.Property<string>("sNombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEstado");

                    b.HasIndex("fkPais");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("GrupoBJ.Models.Pais", b =>
                {
                    b.Property<int>("idPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bHabilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dFechaUsuarioCreo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dFechaUsuarioModifico")
                        .HasColumnType("datetime2");

                    b.Property<int>("fkUsuarioCreo")
                        .HasColumnType("int");

                    b.Property<int>("fkUsuarioModifico")
                        .HasColumnType("int");

                    b.Property<string>("sNombrePais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("GrupoBJ.Models.Ciudad", b =>
                {
                    b.HasOne("GrupoBJ.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("fkEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoBJ.Models.Estado", b =>
                {
                    b.HasOne("GrupoBJ.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("fkPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
